@URL=http://localhost:8080/atuador

### CREATE
POST {{URL}}
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "nome": "teste",
    "dispositivoid": "1"
}

### Obter todos os atuadores
GET {{URL}}
Authorization:Bearer 'token gerado'

### Obter um atuador
GET {{URL}}/'id'
Authorization:Bearer 'token gerado'

### Atualizar um atuador
PUT {{URL}}/'id'
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "nome": "Anas",
    "dispositivoid": 2
}

### Deletar um atuador
DELETE {{URL}}/'id'
Authorization:Bearer 'token gerado'

