@URL=http://localhost:8080/atuador

### CREATE
POST {{URL}}
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "nome": "teste",
    "dispositivoid": "1"
}

### Obter todas as pessoas
GET {{URL}}
Authorization:Bearer 'token gerado'

### Obter um gateway
GET {{URL}}/'id'
Authorization:Bearer 'token gerado'

### Atualizar um gateway
PUT {{URL}}/'id'
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "nome": "Anas",
    "dispositivoid": 2
}

### Deletar uma pessoa
DELETE {{URL}}/'id'
Authorization:Bearer 'token gerado'
