@URL=http://localhost:8080/dispositivo

### CREATE
POST {{URL}}
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "nome": "teste1",
    "descricao": "teste1",
    "localizacao": "11",
    "gatewayid": "1"
    
}

### Obter todas as pessoas
GET {{URL}}
Authorization:Bearer 'token gerado'

### Obter um dispostivo
GET {{URL}}/'id'
Authorization:Bearer 'token gerado'

### Atualizar um dispositivo
PUT {{URL}}/'id'
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "nome": "Anas",
    "descricao": "reste",
    "localizacao": "2,2",
    "gatewayid": "1"
}

### Deletar um dispositivo
DELETE {{URL}}/'id'
Authorization:Bearer 'token gerado'
