@URL=http://localhost:8080/gateway

### CREATE
POST {{URL}}
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "nome": "tessste11",
    "descricao": "tesste1",
    "pessoaid": 1
    
}

### Obter todas os gateways
GET {{URL}}
Authorization:Bearer 'token gerado'

### Obter um gateway
GET {{URL}}/'id'
Authorization:Bearer 'token gerado'

### Atualizar um gateway
PUT {{URL}}/'id'
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "nome": "Anas",
    "descricao": "reste",
    "pessoaid": 2
}

### Deletar um gateway
DELETE {{URL}}/'id'
Authorization:Bearer 'token gerado'
