@URL=http://localhost:8080/leitura

### CREATE
POST {{URL}}
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "valor": 4,
    "sensorid": 1
}

### Obter todas as leituras
GET {{URL}}
Authorization:Bearer 'token gerado'

### Obter uma leitura
GET {{URL}}/id'
Authorization:Bearer 'token gerado'

### Atualizar uma leitura
PUT {{URL}}/'id'
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "valor": 23,
    "sensorid": 2
}

### Deletar uma leitura
DELETE {{URL}}/2
Authorization:Bearer 'token gerado'
