@URL=http://localhost:8080/sensor

### CREATE
POST {{URL}}
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "nome": "testeq",
    "tipo": "testeq",
    "dispositivoid": 1
    
}

### Obter todos os sensores
GET {{URL}}
Authorization:Bearer 'token gerado'

### Obter um sensor
GET {{URL}}/'id'
Authorization:Bearer 'token gerado'

### Atualizar um sensor
PUT {{URL}}/'id'
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "nome": "Anas",
    "tipo": "aa",
    "dispositivoid": 2
}

### Deletar um sensor
DELETE {{URL}}/'id'
Authorization:Bearer 'token gerado'
