@url = http://localhost:3000/evento

###Criar
POST {{url}}
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "nome": "teste",
    "tipo": "testes",
    "dispositivoID": "1",
    "detalhes": "teste"
}

###Atualizar
PUT  {{url}}/'id'
Content-Type: application/json
Authorization:Bearer 'token gerado'

{
    "nome": "teste",
    "tipo": "testes",
    "dispositivoID": "2",
    "detalhes": "2002-09-26"
}

###Deletar
DELETE {{url}}/'id'
Authorization:Bearer 'token gerado'


###GetAll
GET {{url}}
Authorization:Bearer 'token gerado'


###GetID
GET {{url}}/'id'
Authorization:Bearer 'token gerado'

