@url = http://localhost:3000/users

###Criar
POST {{url}}
Content-Type: application/json
Authorization: 

{
    "name": "Ana",
    "email": "ana@hotmail.com",
    "password": "12345",
    "birth": "2002-09-26"
}

###GetAll
GET {{url}}
Authorization: 'token gerado'


###GetID
GET {{url}}/'id'
Authorization: 'token gerado'
